language: node_js
node_js:
  - node

jobs:
  include:
    - addons:
        chrome: stable
      env: BROWSER=ChromeHeadless
    - addons:
        firefox: latest
      env: BROWSER=FirefoxHeadless

cache:
  yarn: true
  npm: true
  directories:
    - www/node_modules

install:
  - yarn bootstrap

after_success:
  - node_modules/.bin/codecov

branches:
  only:
    - master
    - next
