name: Build and Deploy documentation
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Installing Dependencies
      run: yarn bootstrap
    - name: Build documentatation
      run: yarn --cwd www build
    - name: Publish documentation to GitHub Pages
      run: |
        cd www
        git init
        git remote add origin https://github.com/react-bootstrap/react-bootstrap.github.io.git
        git add .
        git commit -m "Updated documentation by GitHub Actions"
        git push origin master --force