name: Node CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        browser: [ChromeHeadless, FirefoxHeadless]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
        - os: macOS-latest
          browser: FirefoxHeadless
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Chrome (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew cask install google-chrome
    - name: Install Dependencies
      run: yarn bootstrap
    - name: Running Tests
      run: yarn test
      env:
        BROWSER: ${{ matrix.browser }}